from tkinter import *
win=Tk()
win.geometry("300x300")
name=Label(win,text="Neme",fg="red")
password=Label(win,text="Password",fg="red")
email=Label(win,text="email ID",fg="red")
eN=Entry(win)
eP=Entry(win)
eE=Entry(win)
def clicked():
    res = "Welcome to " + e.get()
    lbl.configure(text= res)
check=Checkbutton(win,text="Keep me logged in.",command=clicked)
name.grid(row=0)
password.grid(row=1)
email.grid(row=2)
eN.grid(row=0,column=1)
eP.grid(row=1,column=1)
eE.grid(row=2,column=1)
check.grid(row=3,column=1)
"""from tkinter import *
window = Tk()
window.title("Welcome to LikeGeeks app")
window.geometry('350x200')
lbl = Label(window, text="Hello")
lbl.grid(column=0, row=0)
txt = Entry(window,width=10)
txt.grid(column=1, row=0)
def clicked():
    res = "Welcome to " + txt.get()
    lbl.configure(text= res)
btn = Button(window, text="Click Me", command=clicked)
btn.grid(column=2, row=0)
messagebox.showinfo('Message title', 'Message content')
window.mainloop()"""
win.mainloop()